# -*- coding: utf-8 -*-
"""_proj_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/sr-bn98/skills__proj/blob/main/_proj_.ipynb

# Brain Tumor Segmentation Model Trained on 2D MRI Slices

This dataset contains brain MR images together with manual FLAIR abnormality segmentation masks.
The images were obtained from The Cancer Imaging Archive (TCIA).
They correspond to 110 patients included in The Cancer Genome Atlas (TCGA) lower-grade glioma collection with at least fluid-attenuated inversion recovery (FLAIR) sequence and genomic cluster data available ([link](https://www.kaggle.com/datasets/mateuszbuda/lgg-mri-segmentation/code )).

T4 GPU of google colab is used for this session.

**Import Libraries and Installing required libraries**

I use NumPy, Pandas, OpenCV, and scikit-learn for data manipulation, preprocessing, and splitting. For visualizing data and results I use Matplotlib. And finally use Pytorch to build and train deep learning models with various layers and callbacks.
"""

!pip install segmentation_models_pytorch

!pip install torchmetrics

import matplotlib.animation as animation
import os
import random
import numpy as np
import pandas as pd
import cv2
import matplotlib.pyplot as plt
from glob import glob
from tqdm.notebook import tqdm
from torch.utils.data import random_split
from sklearn.model_selection import train_test_split

from rich.console import Console
from rich.table import Table
from google.colab import files
import torch
import torchvision.transforms as transforms
from PIL import Image
from torchmetrics import Dice
import segmentation_models_pytorch as smp
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset , DataLoader ,  random_split
import torchvision.transforms as transforms

"""I also set a seed for reproducibility and consistent results across runs:"""

seed = 40
random.seed(seed)
np.random.seed(seed)
torch.manual_seed(seed)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(seed)

"""# Dataset Familiarization

The dataset is located at https://www.kaggle.com/datasets/mateuszbuda/lgg-mri-segmentation/code Each patient has a folder containing images and masks.
"""

files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json


!kaggle datasets download -d mateuszbuda/lgg-mri-segmentation

!unzip lgg-mri-segmentation.zip  > /dev/null 2>&1

!rm -rf lgg-mri-segmentation.zip

"""There is a folder for each patient, containing images and masks."""

dataset_path = '/content/kaggle_3m'

patients = os.listdir(dataset_path)
print(f"Total patients in the dataset: {len(patients)}")

"""I explore the files in a sample patient's folder to understand the dataset structure, where each patient's image is in .tif format, and the corresponding mask file ends with _mask in its name."""

example_patient = random.choice(patients)
example_patient_path = os.path.join(dataset_path, example_patient)
print(f"Files in {example_patient}:")
print(os.listdir(example_patient_path)[0])

"""Then, I'll get image and mask paths for the example patient:"""

def get_image_mask_paths(patient_path):
    image_paths = glob(os.path.join(patient_path, '*.tif'))
    mask_paths = [path for path in image_paths if 'mask' in os.path.basename(path)]
    image_paths = [path for path in image_paths if 'mask' not in os.path.basename(path)]
    return image_paths, mask_paths

image_paths, mask_paths = get_image_mask_paths(example_patient_path)
print(f"Number of images: {len(image_paths)}, Number of masks: {len(mask_paths)}")

"""# Display 10 Images and Their Corresponding Masks
I've randomly selected 10 images and their corresponding mask paths
Each image is read and converted to Grayscale format and masks are read in Grayscale format.

Contours from the mask are extracted using cv2.findContours and overlaid on the image in red using cv2.drawContours.

The visualization is arranged in three columns:  image,  mask, and the Image with highlighted mask.
"""

num_images_to_display = 10
selected_image_paths = random.sample(image_paths, num_images_to_display)
selected_mask_paths = [path.replace('.tif', '_mask.tif') for path in selected_image_paths]

plt.figure(figsize=(20, 5 * num_images_to_display))

for i, (img_path, mask_path) in enumerate(zip(selected_image_paths, selected_mask_paths)):

    img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
    mask = cv2.imread(mask_path, cv2.IMREAD_COLOR)


    plt.subplot(num_images_to_display, 3, 3 * i + 1)
    plt.imshow(img, cmap='gray')
    plt.title('Image')
    plt.axis('off')



    plt.subplot(num_images_to_display, 3, 3 * i + 2)
    plt.imshow(mask, cmap='gray')
    plt.title('Mask')
    plt.axis('off')



    img_copy = img.copy()
    contours, hier = cv2.findContours(mask[:, :, 0], cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
    mask_over_image = cv2.drawContours(img_copy, contours, -1, [255, 0, 0], thickness=-1)
    plt.subplot(num_images_to_display, 3, 3 * i + 3)
    plt.imshow(mask_over_image)
    plt.title('Image with highlighted mask')
    plt.axis('off')

plt.tight_layout()
plt.show()

"""now i read an image and a mask from their respective file paths and displays basic statistics for both, such as their dimensions, the range of pixel values, and the unique values in the mask (which can be useful to identify different classes or labels in the mask)"""

def load_tiff_images(directory):
    images = []
    for filename in sorted(os.listdir(directory)):
        if filename.endswith(".tif"):
            image_path = os.path.join(directory, filename)
            image = Image.open(image_path)
            images.append(np.array(image))
    return images

def create_animation(images, save_path=None):
    fig, ax = plt.subplots()

    def update(frame):
        ax.imshow(images[frame], cmap='gray')
        ax.set_title(f'Slice {frame + 1}')
        ax.axis('off')

    ani = animation.FuncAnimation(fig, update, frames=len(images), repeat=True)

    if save_path:
        ani.save(save_path, writer='imagemagick')

    plt.show()

tiff_directory = '/content/lgg-mri-segmentation/kaggle_3m/TCGA_CS_4941_19960909'
images = load_tiff_images(tiff_directory)

create_animation(images, save_path='ct_slices_animation.gif')

def display_statistics(image_path, mask_path):
    image = plt.imread(image_path)
    mask = plt.imread(mask_path)

    print("Image Statistics:")
    print(f"Shape: {image.shape}")
    print(f"Min value: {image.min()}")
    print(f"Max value: {image.max()}")

    print("\nMask Statistics:")
    print(f"Shape: {image.shape}")
    print(f"Min value: {image.min()}")
    print(f"Max value: {image.max()}")
    print(f"Unique values: {np.unique(mask)}")

display_statistics(image_paths[0], mask_paths[0])

"""#  Preprocessing
**Implement Image Preprocessing Techniques**

I defined a function to load and preprocess images and their corresponding masks from the dataset and convert them to 'png' format.

because of RAM limitation, i used 3 patients


Read the image in RGB, resize to 128x128, normalize.


Read the mask in grayscale, resize to 128x128, normalize.


Also i used tqdm library to display progress bars for loops. In the code, it wraps the for loop over patient_ids to show how many patient folders have been processed.

"""

def convert_tiff_to_png(tiff_path, output_path):
    """Convert TIFF file to PNG format."""
    tiff_image = Image.open(tiff_path)
    tiff_image.save(output_path, "PNG")


def load_and_preprocess_data(data_path):


    img_png = []
    seg_png = []
    folder_ids = os.listdir(data_path)[:3]
    for folder_id in tqdm(folder_ids, desc='Preprocessing Images and Masks'):
        folder_path = os.path.join(data_path, folder_id)
        image_paths, _ = get_image_mask_paths(folder_path)
        for img_path in image_paths:
            mask_path = img_path.replace('.tif', '_mask.tif')
            new_img_path = img_path.replace('.tif', '.png')
            new_mask_path = mask_path.replace('.tif', '.png')

            convert_tiff_to_png(img_path, new_img_path)
            convert_tiff_to_png(mask_path, new_mask_path)

            img_png.append(new_img_path)
            seg_png.append(new_mask_path)





    return img_png , seg_png

class CustomImageDataset(Dataset):
    def __init__(self, image_path, mask_path, image_transform=None, mask_transform=None):
        self.image_path = image_path
        self.mask_path = mask_path
        self.image_transform = image_transform
        self.mask_transform = mask_transform

    def __len__(self):
        return len(self.image_path)

    def __getitem__(self, idx):
        img_path = self.image_path[idx]
        mask_path = self.mask_path[idx]
        image = Image.open(img_path).convert('RGB')
        mask = Image.open(mask_path).convert('L')

        if self.image_transform:
            image = self.image_transform(image)
        if self.mask_transform:
            mask = self.mask_transform(mask)

        return image, mask


image_transform = transforms.Compose([
    transforms.Resize((128, 128)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])

mask_transform = transforms.Compose([
    transforms.Resize((128, 128)),
    transforms.ToTensor(),
])


img_png,seg_png=load_and_preprocess_data('/content/kaggle_3m')

custom_dataset = CustomImageDataset(img_png,seg_png, image_transform=image_transform ,mask_transform=mask_transform )

"""# Split the Dataset into Train and Test Sets

split into train and test (train is 80%, test is 20%)
"""

train_size = int(0.8 * len(custom_dataset))
test_size = len(custom_dataset) - train_size


train_ds, test_ds = random_split(custom_dataset, [train_size, test_size])

"""# Set Dataloader"""

train_loader = DataLoader(dataset=train_ds, batch_size=16, shuffle=True)

"""#  Visualization
This function is to show 5 patients from our datasets, so that we can see if the it is okay or we need
to change/delete something.




"""

num_samples_to_display = 5
samples_displayed = 0

for images, masks in train_loader:
    for i in range(images.shape[0]):
        img = images[i].cpu().numpy().transpose(1, 2, 0)
        mask = masks[i].cpu().numpy().squeeze()
        img = (img - img.min()) / (img.max() - img.min())

        plt.figure(figsize=(8, 4))
        plt.subplot(1, 2, 1)
        plt.imshow(img)
        plt.title('Image')
        plt.axis('off')

        plt.subplot(1, 2, 2)
        plt.imshow(mask, cmap='gray')
        plt.title('Mask')
        plt.axis('off')

        plt.show()

        samples_displayed += 1
        if samples_displayed >= num_samples_to_display:
            break

    if samples_displayed >= num_samples_to_display:
        break

"""# Define our Model"""

model = smp.Unet(
    encoder_name="resnet34",
    in_channels=3,
    classes=1,
    activation='sigmoid'
)

"""# Set our Optimizer and Loss function and Metrics"""

optimizer = optim.Adam(model.parameters(), lr=0.001)

class DiceLoss(nn.Module):
    def __init__(self):
        super(DiceLoss, self).__init__()

    def forward(self, inputs, targets, smooth=1):
        inputs = inputs.view(-1)
        targets = targets.view(-1)

        intersection = (inputs * targets).sum()
        dice = (2. * intersection + smooth) / (inputs.sum() + targets.sum() + smooth)

        return 1 - dice


dice_metric = Dice()

!mkdir '/content/model'

"""# Our Training Process"""

def train_one_epoch(model, train_loader, criterion, optimizer, device):
    model.train()
    train_loss = 0.0
    dice_metric = Dice().to(device)

    for images, masks in tqdm(train_loader):
        images, masks = images.to(device), masks.to(device)
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, masks)
        loss.backward()
        optimizer.step()
        train_loss += loss.item() * images.size(0)

        dice_metric.update(outputs, masks.int())

    train_loss /= len(train_loader.dataset)
    dice_score = dice_metric.compute().item()

    return train_loss, dice_score

def validate_one_epoch(model, val_loader, criterion, device):
    model.eval()
    val_loss = 0.0
    dice_metric = Dice().to(device)

    with torch.no_grad():
        for images, masks in val_loader:
            images, masks = images.to(device), masks.to(device)
            outputs = model(images)
            loss = criterion(outputs, masks)
            val_loss += loss.item() * images.size(0)

            dice_metric.update(outputs, masks.int())

    val_loss /= len(val_loader.dataset)
    dice_score = dice_metric.compute().item()

    return val_loss, dice_score

def train_and_validate(train_dataset,val_dataset,
                       model, device, num_epochs, batch_size):

    train_dataset = train_dataset
    val_dataset =val_dataset
    import torch


    model_save_path = '/content/model.pth'


    train_loader = DataLoader(
        train_dataset,
        batch_size=batch_size,
        shuffle=True,
        num_workers=4,
        pin_memory=True
    )
    val_loader = DataLoader(
        val_dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=4,
        pin_memory=True
    )

    model = model.to(device)
    criterion = DiceLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

    best_val_loss = float('inf')
    train_losses = []
    val_losses = []
    train_dices = []
    val_dices = []

    for epoch in range(num_epochs):
        train_loss, train_dice = train_one_epoch(model, train_loader, criterion, optimizer, device)
        val_loss, val_dice = validate_one_epoch(model, val_loader, criterion, device)

        train_losses.append(train_loss)
        val_losses.append(val_loss)
        train_dices.append(train_dice)
        val_dices.append(val_dice)

        print(f'Epoch {epoch+1}/{num_epochs}, Train Loss: {train_loss:.4f}, Val Loss: {val_loss:.4f}, Train Dice: {train_dice:.4f}, Val Dice: {val_dice:.4f}')

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            torch.save(model.state_dict(), model_save_path)

    return train_losses, val_losses, train_dices, val_dices

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Using {device} device...')

train_losses, val_losses, train_dices, val_dices = train_and_validate(
    train_ds,
    test_ds,
    model,
    device,
    num_epochs=20,
    batch_size=16
)

"""# Resuls and Analysis"""

def plot_progress(train_losses, val_losses, train_dices, val_dices , savefig):
    num_epochs = len(train_losses)
    plt.figure(figsize=(12, 6))


    plt.subplot(1, 2, 1)
    plt.plot(range(1, num_epochs+1), train_losses, label='Train Loss')
    plt.plot(range(1, num_epochs+1), val_losses, label='Val Loss')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.title('Training and Validation Loss')
    plt.legend()


    plt.subplot(1, 2, 2)
    plt.plot(range(1, num_epochs+1), train_dices, label='Train Dice')
    plt.plot(range(1, num_epochs+1), val_dices, label='Val Dice')
    plt.xlabel('Epoch')
    plt.ylabel('Dice Score')
    plt.title('Training and Validation Dice Scores')
    plt.legend()

    plt.tight_layout()
    plt.savefig(savefig)
    plt.show()

plot_progress(train_losses, val_losses, train_dices, val_dices,'/content/model.png')

best_model = smp.Unet(
    encoder_name="resnet34",
    in_channels=3,
    classes=1,
    activation='sigmoid'
)
state_dict = torch.load('/content/model.pth')
best_model.load_state_dict(state_dict)
best_model = best_model.to(device)
criterion = DiceLoss()


test_loader = DataLoader(
    test_ds,
    batch_size=16,
    shuffle=True,
    num_workers=4,
    pin_memory=True
)

test_loss, test_dice = validate_one_epoch(
    best_model, test_loader, criterion, device
)

print(f'Test loss: {test_loss:.4f}')
print(f'Test dice: {test_dice:.4f}')

"""# Display 5 Test Images, Ground Truths, and Their Corresponding Generated Masks"""

for images, masks in test_loader:
    images, masks = images.to(device), masks.to(device)
    outputs = best_model(images)

    fig, axs = plt.subplots(9, 3, figsize=(8, 10))
    axs[0, 0].set_title('Image')
    axs[0, 1].set_title('Ground Truth')
    axs[0, 2].set_title('Prediction')

    indices = list(range(images.size(0)))
    random.shuffle(indices)

    samples_displayed = 0
    num_samples_to_display = 9

    for i in range(num_samples_to_display):
        index = indices[i]

        img = images[index].cpu().numpy().transpose(1, 2, 0)
        mask = masks[index].cpu().numpy().squeeze()
        img = (img - img.min()) / (img.max() - img.min())
        pred = outputs[index].cpu().detach().numpy().squeeze()

        axs[i, 0].imshow(img)
        axs[i, 1].imshow(mask, cmap='gray')
        axs[i, 2].imshow(pred, cmap='gray')

        for j in range(3):
            axs[i, j].axis('off')

        samples_displayed += 1

    break

plt.tight_layout()
plt.show()

!python -c "import monai" || pip install -qU "monai[ignite, nibabel, torchvision, tqdm]==1.2.0"

from monai.networks.nets  import UNet
from monai.losses import DiceLoss
from monai.metrics import DiceMetric



device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')


monai_model = UNet(
    spatial_dims=2,
    in_channels=3,
    out_channels=1,
    channels=(64, 128, 256, 512),
    strides=(2, 2, 2),
    num_res_units=2
)

def dice_metric(predicted, target):

    dice_value = DiceLoss(to_onehot_y=True, sigmoid=True, squared_pred=True)
    value = 1 - dice_value(predicted, target).item()
    return value

!mkdir monai_model

def train_and_validate_moani(train_dataset,val_dataset,
                       model, device, num_epochs, batch_size):

    train_dataset = train_dataset
    val_dataset =val_dataset
    import torch


    model_save_path = '/content/monaimodel.pth'


    train_loader = DataLoader(
        train_dataset,
        batch_size=batch_size,
        shuffle=True,
        num_workers=4,
        pin_memory=True
    )
    val_loader = DataLoader(
        val_dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=4,
        pin_memory=True
    )

    model = model.to(device)
    criterion = DiceLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

    best_val_loss = float('inf')
    train_losses = []
    val_losses = []
    train_dices = []
    val_dices = []

    for epoch in range(num_epochs):
        train_loss, train_dice = train_one_epoch(model, train_loader, criterion, optimizer, device)
        val_loss, val_dice = validate_one_epoch(model, val_loader, criterion, device)

        train_losses.append(train_loss)
        val_losses.append(val_loss)
        train_dices.append(train_dice)
        val_dices.append(val_dice)

        print(f'Epoch {epoch+1}/{num_epochs}, Train Loss: {train_loss:.4f}, Val Loss: {val_loss:.4f}, Train Dice: {train_dice:.4f}, Val Dice: {val_dice:.4f}')

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            torch.save(model.state_dict(), model_save_path)

    return train_losses, val_losses, train_dices, val_dices

train_losses, val_losses, train_dices, val_dices = train_and_validate_moani(
    train_ds,
    test_ds,
    monai_model,
    device,
    num_epochs=20,
    batch_size=16
)

plot_progress(train_losses, val_losses, train_dices, val_dices,'/content/monaimodel.png')

best_model_monai = UNet(
    spatial_dims=2,
    in_channels=3,
    out_channels=1,
    channels=(64, 128, 256, 512),
    strides=(2, 2, 2),
    num_res_units=2
)
state_dict = torch.load('/content/monaimodel.pth')
best_model_monai.load_state_dict(state_dict)
best_model_monai = best_model_monai.to(device)
criterion = DiceLoss()


test_loader = DataLoader(
    test_ds,
    batch_size=16,
    shuffle=True,
    num_workers=4,
    pin_memory=True
)

test_loss, test_dice = validate_one_epoch(
    best_model_monai, test_loader, criterion, device
)

print(f'Test loss: {test_loss:.4f}')
print(f'Test dice: {test_dice:.4f}')

for images, masks in test_loader:
    images, masks = images.to(device), masks.to(device)
    outputs = best_model_monai(images)

    fig, axs = plt.subplots(9, 3, figsize=(8, 10))
    axs[0, 0].set_title('Image')
    axs[0, 1].set_title('Ground Truth')
    axs[0, 2].set_title('Prediction')

    indices = list(range(images.size(0)))
    random.shuffle(indices)

    samples_displayed = 0
    num_samples_to_display = 9

    for i in range(num_samples_to_display):
        index = indices[i]

        img = images[index].cpu().numpy().transpose(1, 2, 0)
        mask = masks[index].cpu().numpy().squeeze()
        img = (img - img.min()) / (img.max() - img.min())
        pred = outputs[index].cpu().detach().numpy().squeeze()

        axs[i, 0].imshow(img)
        axs[i, 1].imshow(mask, cmap='gray')
        axs[i, 2].imshow(pred, cmap='gray')

        for j in range(3):
            axs[i, j].axis('off')

        samples_displayed += 1

    break

plt.tight_layout()
plt.show()

"""# Limitations

* The dataset we used for training may not be large enough
for training highly complex deep learning models, which often require extensive data to generalize well.


* There might be an imbalance in the segmentation labels (e.g., fewer abnormal regions compared to normal ones), which can affect model performance.

* Leaking Future Information: In machine learning, if training data contains information that is also present in the testing data, the model's evaluation will be biased, leading to artificially high performance metrics. For example, if the same image appears in both training and testing sets, it undermines the model's ability to generalize to new, unseen data.

* The outpu of `create_animation` can be played only in Files pane

* The negative value of `Test loss: -0.1482` in best_model_monai

.



"""